"""
AI Coach and Workout Generation Service.

Integrates with Anthropic Claude API to generate personalized workout routines,
stream interactive coaching chat responses with context injection,
and analyze progressive overload suggestions based on workout history.
"""

import json
from typing import Generator, List, Dict, Any
from anthropic import Anthropic
from pydantic import TypeAdapter
from sqlalchemy.orm import Session
from app.config import settings
from app.schemas.plan import ProgressSuggestion

# Initialize Anthropic Claude API client
client = Anthropic(api_key=settings.anthropic_api_key.get_secret_value(), timeout=60.0, max_retries=1)

# System prompt instructing Claude to generate structured JSON workout plans
PLAN_SYSTEM_PROMPT = """You are an expert strength and conditioning coach.
Return ONLY valid JSON, no markdown, no explanation. Schema:
{"weeks": <int>, "days": [{"day": "<name>", "focus": "<focus>", "exercises": 
[{"name": "<name>", "sets": <int>, "reps": "<e.g. 6-8>", "rest_seconds": <int>}]}]}"""


def _strip_code_fences(text: str) -> str:
    """
    Strips markdown code fences (e.g., ```json ... ```) from model completions
    to ensure reliable json.loads parsing.
    
    Args:
        text: Raw text response from LLM.
        
    Returns:
        str: Cleaned JSON string.
    """
    text = text.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text[3:]
        text = text.rsplit("```", 1)[0]
    return text.strip()


def generate_plan(user) -> dict:
    """
    Generates a personalized multi-week workout plan tailored to user's biometrics and goals.
    
    Args:
        user: SQLAlchemy User model instance containing age, goals, equipment, and injuries.
        
    Returns:
        dict: Parsed workout plan JSON structure.
    """
    profile = (
        f"Age: {user.age}, Gender: {user.gender}, Weight_kg: {user.weight_kg}, "
        f"Goal: {user.goal}, Level: {user.level}, Days_per_week: {user.days_per_week}, "
        f"Equipment: {user.equipment}, Injuries: {user.injuries}"
    )

    response = client.messages.create(
        model="claude-haiku-4-5",
        max_tokens=2000,
        system=PLAN_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": profile}]
    )
    answer = response.content[0].text.strip()
    answer = _strip_code_fences(answer)
    return json.loads(answer)


def build_coach_system_prompt(user, db: Session) -> str:
    """
    Builds a dynamic context-aware system prompt for the AI Coach chat.
    Injects the user's active workout plan and recent session performance into the context.
    
    Args:
        user: Authenticated User model instance.
        db: Scoped database session.
        
    Returns:
        str: Fully compiled system prompt for Claude.
    """
    from app.models.plan import WorkoutPlan
    from app.models.session import WorkoutSession, ExerciseLog

    # Fetch user's currently active workout plan
    active_plan = db.query(WorkoutPlan).filter(
        WorkoutPlan.is_active == True,
        WorkoutPlan.user_id == user.id
    ).first()

    # Fetch last 3 recorded workout sessions to provide recent exercise context
    w_sessions = db.query(WorkoutSession).filter(
        WorkoutSession.user_id == user.id
    ).order_by(WorkoutSession.session_date.desc()).limit(3).all()

    # Build a serializable summary of recent sessions
    sessions_summary = []
    for s in w_sessions:
        exercises = []
        for log in db.query(ExerciseLog).filter(ExerciseLog.session_id == s.id).all():
            exercises.append({"exercise": log.exercise_name, "sets": log.sets_data})
        sessions_summary.append({"date": str(s.session_date), "exercises": exercises})

    profile = (
        f"Age: {user.age}, Gender: {user.gender}, Weight_kg: {user.weight_kg}, "
        f"Goal: {user.goal}, Level: {user.level}, Days_per_week: {user.days_per_week}, "
        f"Equipment: {user.equipment}, Injuries: {user.injuries}, "
        f"Plan: {json.dumps(active_plan.plan_data) if active_plan else 'none'}, "
        f"Recent sessions: {json.dumps(sessions_summary)}"
    )

    return f"""You are FitAI, an expert AI fitness coach. You have access to the user's profile and workout data.
Be helpful, motivating, and specific. Give evidence-based advice.
If you don't know something, say so rather than guessing.

User profile and context:
{profile}"""


def stream_chat(user, messages: List[Dict[str, str]], db: Session) -> Generator[str, None, None]:
    """
    Streams conversational tokens from Claude via Server-Sent Events (SSE).
    
    Args:
        user: Authenticated User model instance.
        messages: Conversation history list formatted as [{'role': '...', 'content': '...'}].
        db: Scoped database session.
        
    Yields:
        str: Incremental text tokens as generated by Claude.
    """
    system = build_coach_system_prompt(user, db)
    with client.messages.stream(
        model="claude-haiku-4-5",
        max_tokens=1000,
        system=system,
        messages=messages
    ) as stream:
        for text in stream.text_stream:
            yield text


def get_progressive_overload_suggestions(user, db: Session) -> List[Dict[str, Any]]:
    """
    Analyzes user's last several workout sessions to recommend progressive overload adjustments
    (e.g., increase weight, add an extra rep, or adjust rest intervals).
    
    Args:
        user: Authenticated User model instance.
        db: Scoped database session.
        
    Returns:
        List[Dict[str, Any]]: Array of suggestion objects: [{"exercise": ..., "suggestion": ...}].
    """
    from app.models.session import WorkoutSession, ExerciseLog

    sessions = db.query(WorkoutSession).filter(
        WorkoutSession.user_id == user.id
    ).order_by(WorkoutSession.session_date.desc()).limit(6).all()

    # Need at least 2 sessions to evaluate progress trends
    if len(sessions) < 2:
        return []

    # Map exercise history chronologically
    history = {}
    for s in sessions:
        for log in db.query(ExerciseLog).filter(ExerciseLog.session_id == s.id).all():
            history.setdefault(log.exercise_name, []).append(
                {"date": str(s.session_date), "sets": log.sets_data}
            )

    if not history:
        return []

    prompt = f"""Analyze workout history. Return ONLY a JSON array (no markdown, no code fences):
    [{{"exercise": "name", "suggestion": "specific next-session suggestion"}}]
    History: {json.dumps(history)}"""

    response = client.messages.create(
        model="claude-haiku-4-5",
        max_tokens=500,
        messages=[{"role": "user", "content": prompt}]
    )

    answer = response.content[0].text.strip()
    answer = _strip_code_fences(answer)
    parsed = json.loads(answer)
    suggestions = TypeAdapter(List[ProgressSuggestion]).validate_python(parsed)
    if len(suggestions) > 20:
        raise ValueError("Too many progress suggestions")
    return [suggestion.model_dump() for suggestion in suggestions]
